In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

Phase 1
Data Collection/preparation part.
We will work on each data separately and then concat all the dataframes togther

The population of each state.

Literacy Rate in each state

Area of each state

In [2]:
data=pd.read_csv(r"E:\crime1.csv",encoding='latin1')
data

STATE/UT                   STATE/UT.1    Population  \
0                 Uttar Pradesh                UTTAR PRADESH  19,95,81,477   
1                   Maharashtra                  MAHARASHTRA  11,23,72,972   
2                         Bihar                        BIHAR  10,38,04,630   
3                   West Bengal                  WEST BENGAL   9,13,47,736   
4                Andhra Pradesh               ANDHRA PRADESH   7,25,97,565   
5                    Tamil Nadu                   TAMIL NADU   7,21,38,958   
6                Madhya Pradesh               MADHYA PRADESH   6,86,21,012   
7                     Rajasthan                    RAJASTHAN   6,11,30,704   
8                     Karnataka                    KARNATAKA   6,03,83,628   
9                       Gujarat                      GUJARAT   4,93,86,799   
10                       Odisha                       ODISHA   4,19,47,358   
11                       Kerala                       KERALA   3,51,93,978   
12                    Jharkhand                    JHARKHAND   3,33,87,677   
13                        Assam                        ASSAM   3,29,88,134   
14                       Punjab                       PUNJAB   3,11,69,272   
15                      Haryana                      HARYANA   2,77,04,236   
16                 Chhattisgarh                 CHHATTISGARH   2,57,53,081   
17                        Delhi                        DELHI   2,55,40,196   
18            Jammu and Kashmir            JAMMU AND KASHMIR   1,25,48,926   
19                  Uttarakhand                  UTTARAKHAND   1,01,16,752   
20             Himachal Pradesh             HIMACHAL PRADESH     68,56,509   
21                      Tripura                      TRIPURA     36,71,032   
22                    Meghalaya                    MEGHALAYA     29,64,007   
23                      Manipur                      MANIPUR     27,21,756   
24                     Nagaland                     NAGALAND     19,80,602   
25                          Goa                          GOA     14,57,723   
26            Arunachal Pradesh            ARUNACHAL PRADESH     13,82,611   
27                      Mizoram                      MIZORAM     10,91,014   
28                       Sikkim                       SIKKIM      6,07,688   
29                   Puducherry                   PUDUCHERRY   1,67,53,235   
30                   Chandigarh                   CHANDIGARH     12,44,464   
31  Andaman and Nicobar Islands  ANDAMAN AND NICOBAR ISLANDS     10,54,686   
32       Dadra and Nagar Haveli       DADRA AND NAGAR HAVELI      3,79,944   
33                Daman and Diu                DAMAN AND DIU      3,42,853   
34                  Lakshadweep                  LAKSHADWEEP      2,42,911   
35                          NaN                          NaN           NaN   

    Literacy Area (km2)  
0      67.68   2,40,928  
1      82.34   3,07,713  
2      61.80     94,163  
3      76.26     88,752  
4      67.02   1,62,975  
5      80.09   1,30,058  
6      69.32   3,08,252  
7      66.11   3,42,239  
8      75.36   1,91,791  
9      78.03   1,96,024  
10     72.87   1,55,707  
11     94.00     38,863  
12     66.41     79,716  
13     72.19     78,438  
14     75.84     50,362  
15     75.55     44,212  
16     70.28   1,35,192  
17     86.21      1,484  
18     67.16     42,241  
19     78.82     53,483  
20     82.80     55,673  
21     87.22     10,491  
22     74.43     22,429  
23     76.94     22,327  
24     79.55     16,579  
25     88.70      3,702  
26     65.38     83,743  
27     91.33     21,081  
28     81.42      7,096  
29     85.85        479  
30     86.05        114  
31     86.63      8,249  
32     76.24        603  
33     87.10        603  
34     91.85         32  
35       NaN        NaN

The following data has been taken from wikipedia.Attached are the links: 1.Population: https://en.wikipedia.org/w/index.php?title=List_of_states_in_India_by_past_population&section=2&oldid=1163880358&action=edit 2.Literacy : https://www.census2011.co.in/literacy.php 3.Area statewise: https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area

In [3]:
data.dropna(axis=0,inplace=True)

In [4]:
data.drop(['STATE/UT'],axis=1,inplace=True)

In [5]:
data.rename(columns={'STATE/UT.1': 'State','Area (km2)':'Area'}, inplace=True)
data

State    Population  Literacy      Area
0                 UTTAR PRADESH  19,95,81,477     67.68  2,40,928
1                   MAHARASHTRA  11,23,72,972     82.34  3,07,713
2                         BIHAR  10,38,04,630     61.80    94,163
3                   WEST BENGAL   9,13,47,736     76.26    88,752
4                ANDHRA PRADESH   7,25,97,565     67.02  1,62,975
5                    TAMIL NADU   7,21,38,958     80.09  1,30,058
6                MADHYA PRADESH   6,86,21,012     69.32  3,08,252
7                     RAJASTHAN   6,11,30,704     66.11  3,42,239
8                     KARNATAKA   6,03,83,628     75.36  1,91,791
9                       GUJARAT   4,93,86,799     78.03  1,96,024
10                       ODISHA   4,19,47,358     72.87  1,55,707
11                       KERALA   3,51,93,978     94.00    38,863
12                    JHARKHAND   3,33,87,677     66.41    79,716
13                        ASSAM   3,29,88,134     72.19    78,438
14                       PUNJAB   3,11,69,272     75.84    50,362
15                      HARYANA   2,77,04,236     75.55    44,212
16                 CHHATTISGARH   2,57,53,081     70.28  1,35,192
17                        DELHI   2,55,40,196     86.21     1,484
18            JAMMU AND KASHMIR   1,25,48,926     67.16    42,241
19                  UTTARAKHAND   1,01,16,752     78.82    53,483
20             HIMACHAL PRADESH     68,56,509     82.80    55,673
21                      TRIPURA     36,71,032     87.22    10,491
22                    MEGHALAYA     29,64,007     74.43    22,429
23                      MANIPUR     27,21,756     76.94    22,327
24                     NAGALAND     19,80,602     79.55    16,579
25                          GOA     14,57,723     88.70     3,702
26            ARUNACHAL PRADESH     13,82,611     65.38    83,743
27                      MIZORAM     10,91,014     91.33    21,081
28                       SIKKIM      6,07,688     81.42     7,096
29                   PUDUCHERRY   1,67,53,235     85.85       479
30                   CHANDIGARH     12,44,464     86.05       114
31  ANDAMAN AND NICOBAR ISLANDS     10,54,686     86.63     8,249
32       DADRA AND NAGAR HAVELI      3,79,944     76.24       603
33                DAMAN AND DIU      3,42,853     87.10       603
34                  LAKSHADWEEP      2,42,911     91.85        32

In [6]:
df1=pd.read_csv(r'E:\India_Crime - Copy\crime a.csv')
df1

STATE/UT       DISTRICT  YEAR  MURDER  ATTEMPT TO MURDER  \
0     ANDHRA PRADESH       ADILABAD  2001     101                 60   
1     ANDHRA PRADESH      ANANTAPUR  2001     151                125   
2     ANDHRA PRADESH       CHITTOOR  2001     101                 57   
3     ANDHRA PRADESH       CUDDAPAH  2001      80                 53   
4     ANDHRA PRADESH  EAST GODAVARI  2001      82                 67   
...              ...            ...   ...     ...                ...   
9012     LAKSHADWEEP    LAKSHADWEEP  2012       0                  0   
9013     LAKSHADWEEP          TOTAL  2012       0                  0   
9014      PUDUCHERRY       KARAIKAL  2012       5                  6   
9015      PUDUCHERRY     PUDUCHERRY  2012      24                 21   
9016      PUDUCHERRY          TOTAL  2012      29                 27   

      CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  RAPE  CUSTODIAL RAPE  \
0                                            17    50               0   
1                                             1    23               0   
2                                             2    27               0   
3                                             1    20               0   
4                                             1    23               0   
...                                         ...   ...             ...   
9012                                          0     0               0   
9013                                          0     0               0   
9014                                          2     6               0   
9015                                         10     7               0   
9016                                         12    13               0   

      OTHER RAPE  KIDNAPPING & ABDUCTION  ...  ARSON  HURT/GREVIOUS HURT  \
0             50                      46  ...     30                1131   
1             23                      53  ...     69                1543   
2             27                      59  ...     38                2088   
3             20                      25  ...     23                 795   
4             23                      49  ...     41                1244   
...          ...                     ...  ...    ...                 ...   
9012           0                       0  ...      3                   3   
9013           0                       0  ...      3                   3   
9014           6                       2  ...      1                 186   
9015           7                      17  ...     20                 632   
9016          13                      19  ...     21                 818   

      DOWRY DEATHS  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0               16                                                149     
1                7                                                118     
2               14                                                112     
3               17                                                126     
4               12                                                109     
...            ...                                                ...     
9012             0                                                  1     
9013             0                                                  1     
9014             0                                                  2     
9015             0                                                  7     
9016             0                                                  9     

      INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
0                             34                                  175   
1                             24                                  154   
2                             83                                  186   
3                             38                                   57   
4                             58                                  247   
...               

I have dropped following coloumns:
district as we already have the states present, we already have the no of total rape columns as Rape same with kidnappinf and theft columns as there is already one column having total value of rape,kidnap,theft 

In [7]:
df1.drop(['DISTRICT','CUSTODIAL RAPE','OTHER RAPE','KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS','KIDNAPPING AND ABDUCTION OF OTHERS','AUTO THEFT','OTHER THEFT'],axis=1,inplace=True)

In [8]:
df1.rename(columns={'STATE/UT': 'State','YEAR':'Year','MURDER':'Murder','ATTEMPT TO MURDER':'Attempt to murder','CULPABLE HOMICIDE NOT AMOUNTING TO MURDER':'Culpable homicide not amounting to muder','RAPE':'Rape','KIDNAPPING & ABDUCTION':'Kidnapping and Abduction','DACOITY':'Dacoity','PREPARATION AND ASSEMBLY FOR DACOITY':'Preparation and assembly for dacoity','ROBBERY':'Robbery','BURGLARY':'Burglary','THEFT':'Theft','RIOTS':'Riots',' CRIMINAL BREACH OF TRUST':'Criminal breach of trust','CHEATING':'Cheating',' COUNTERFIETING':'Counterfieting',' ARSON':'Arson',' HURT/GREVIOUS HURT':'Hurt','DOWRY DEATHS':'Dowry Deaths','ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY':'Assault on women with intent to outrage her modesty','INSULT TO MODESTY OF WOMEN':'Insult to modesty of Women','CRUELTY BY HUSBAND OR HIS RELATIVES':'Cruelty by Husband or his Relatives','IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES':'Importation of Girls','CAUSING DEATH BY NEGLIGENCE':'Causing death by negligence'}, inplace=True)
df1.head()

State  Year  Murder  Attempt to murder  \
0  ANDHRA PRADESH  2001     101                 60   
1  ANDHRA PRADESH  2001     151                125   
2  ANDHRA PRADESH  2001     101                 57   
3  ANDHRA PRADESH  2001      80                 53   
4  ANDHRA PRADESH  2001      82                 67   

   Culpable homicide not amounting to muder  Rape  Kidnapping and Abduction  \
0                                        17    50                        46   
1                                         1    23                        53   
2                                         2    27                        59   
3                                         1    20                        25   
4                                         1    23                        49   

   Dacoity  Preparation and assembly for dacoity  Robbery  ...  ARSON  \
0        9                                     0       41  ...     30   
1        8                                     0       16  ...     69   
2        4                                     0       14  ...     38   
3        1                                     0        4  ...     23   
4        4                                     0       25  ...     41   

   HURT/GREVIOUS HURT  Dowry Deaths  \
0                1131            16   
1                1543             7   
2                2088            14   
3                 795            17   
4                1244            12   

   Assault on women with intent to outrage her modesty  \
0                                                149     
1                                                118     
2                                                112     
3                                                126     
4                                                109     

   Insult to modesty of Women  Cruelty by Husband or his Relatives  \
0                          34                                  175   
1                          24                                  154   
2                          83                                  186   
3                          38                                   57   
4                          58                                  247   

   Importation of Girls  Causing death by negligence  OTHER IPC CRIMES  \
0                     0                          181              1518   
1                     0                          270               754   
2                     0                          404              1262   
3                     0                          233              1181   
4                     0                          431              2313   

   TOTAL IPC CRIMES  
0              4154  
1              4125  
2              5818  
3              3140  
4              6507  

[5 rows x 26 columns]

In [9]:
df1.rename(columns={'ARSON': 'Arson','HURT/GREVIOUS HURT':'Hurt'}, inplace=True)
df1

State  Year  Murder  Attempt to murder  \
0     ANDHRA PRADESH  2001     101                 60   
1     ANDHRA PRADESH  2001     151                125   
2     ANDHRA PRADESH  2001     101                 57   
3     ANDHRA PRADESH  2001      80                 53   
4     ANDHRA PRADESH  2001      82                 67   
...              ...   ...     ...                ...   
9012     LAKSHADWEEP  2012       0                  0   
9013     LAKSHADWEEP  2012       0                  0   
9014      PUDUCHERRY  2012       5                  6   
9015      PUDUCHERRY  2012      24                 21   
9016      PUDUCHERRY  2012      29                 27   

      Culpable homicide not amounting to muder  Rape  \
0                                           17    50   
1                                            1    23   
2                                            2    27   
3                                            1    20   
4                                            1    23   
...                                        ...   ...   
9012                                         0     0   
9013                                         0     0   
9014                                         2     6   
9015                                        10     7   
9016                                        12    13   

      Kidnapping and Abduction  Dacoity  Preparation and assembly for dacoity  \
0                           46        9                                     0   
1                           53        8                                     0   
2                           59        4                                     0   
3                           25        1                                     0   
4                           49        4                                     0   
...                        ...      ...                                   ...   
9012                         0        0                                     0   
9013                         0        0                                     0   
9014                         2        0                                     1   
9015                        17        5                                    14   
9016                        19        5                                    15   

      Robbery  ...  Arson  Hurt  Dowry Deaths  \
0          41  ...     30  1131            16   
1          16  ...     69  1543             7   
2          14  ...     38  2088            14   
3           4  ...     23   795            17   
4          25  ...     41  1244            12   
...       ...  ...    ...   ...           ...   
9012        0  ...      3     3             0   
9013        0  ...      3     3             0   
9014        3  ...      1   186             0   
9015       13  ...     20   632             0   
9016       16  ...     21   818             0   

      Assault on women with intent to outrage her modesty  \
0                                                   149     
1                                                   118     
2                                                   112     
3                                                   126     
4                                                   109     
...                                                 ...     
9012                                                  1     
9013                                                  1     
9014                                                  2     
9015                                                  7     
9016                                                  9     

      Insult to modesty of Women  Cruelty by Husband or his Relatives  \
0                             34                                  175   
1                             24                                  154   
2                             83                                  186   
3                             38                                   57 

In [10]:
df2=pd.read_csv(r'E:\India_Crime - Copy\crime b.csv')
df2

STATE/UT       DISTRICT  Year  Murder  Rape  \
0     ANDHRA PRADESH       ADILABAD  2001       0     1   
1     ANDHRA PRADESH      ANANTAPUR  2001       0     4   
2     ANDHRA PRADESH       CHITTOOR  2001       3     3   
3     ANDHRA PRADESH       CUDDAPAH  2001       0     3   
4     ANDHRA PRADESH  EAST GODAVARI  2001       1     3   
...              ...            ...   ...     ...   ...   
9013     LAKSHADWEEP    LAKSHADWEEP  2012       0     0   
9014     LAKSHADWEEP          TOTAL  2012       0     0   
9015      PUDUCHERRY       KARAIKAL  2012       1     0   
9016      PUDUCHERRY     PUDUCHERRY  2012       1     0   
9017      PUDUCHERRY          TOTAL  2012       2     0   

      Kidnapping and Abduction  Dacoity  Robbery  Arson  Hurt  \
0                            4        0        0      0     3   
1                            0        0        0      0    49   
2                            0        0        0      0    38   
3                            0        0        0      0    20   
4                            0        0        0      0     3   
...                        ...      ...      ...    ...   ...   
9013                         0        0        0      0     0   
9014                         0        0        0      0     0   
9015                         0        0        0      0     0   
9016                         0        0        0      0     0   
9017                         0        0        0      0     0   

      Prevention of atrocities (POA) Act  \
0                                      0   
1                                     21   
2                                     36   
3                                     52   
4                                     12   
...                                  ...   
9013                                   0   
9014                                   0   
9015                                   0   
9016                                   1   
9017                                   1   

      Protection of Civil Rights (PCR) Act  Other Crimes Against SCs  
0                                       15                        32  
1                                        0                        53  
2                                        0                        34  
3                                        0                        25  
4                                       63                         7  
...                                    ...                       ...  
9013                                     0                         0  
9014                                     0                         0  
9015                                     0                         0  
9016                                    20                         1  
9017                                    20                         1  

[9018 rows x 13 columns]

In [11]:
df2.rename(columns={'STATE/UT': 'State'}, inplace=True)
df2.head()

State       DISTRICT  Year  Murder  Rape  \
0  ANDHRA PRADESH       ADILABAD  2001       0     1   
1  ANDHRA PRADESH      ANANTAPUR  2001       0     4   
2  ANDHRA PRADESH       CHITTOOR  2001       3     3   
3  ANDHRA PRADESH       CUDDAPAH  2001       0     3   
4  ANDHRA PRADESH  EAST GODAVARI  2001       1     3   

   Kidnapping and Abduction  Dacoity  Robbery  Arson  Hurt  \
0                         4        0        0      0     3   
1                         0        0        0      0    49   
2                         0        0        0      0    38   
3                         0        0        0      0    20   
4                         0        0        0      0     3   

   Prevention of atrocities (POA) Act  Protection of Civil Rights (PCR) Act  \
0                                   0                                    15   
1                                  21                                     0   
2                                  36                                     0   
3                                  52                                     0   
4                                  12                                    63   

   Other Crimes Against SCs  
0                        32  
1                        53  
2                        34  
3                        25  
4                         7

In [12]:
df3=pd.read_csv(r'E:\India_Crime - Copy\crime c.csv')
df3.head()

STATE/UT       DISTRICT  Year  Murder  Rape  Kidnapping Abduction  \
0  ANDHRA PRADESH       ADILABAD  2001       0     1                     2   
1  ANDHRA PRADESH      ANANTAPUR  2001       0     0                     0   
2  ANDHRA PRADESH       CHITTOOR  2001       0     0                     0   
3  ANDHRA PRADESH       CUDDAPAH  2001       0     0                     0   
4  ANDHRA PRADESH  EAST GODAVARI  2001       0     0                     0   

   Dacoity  Robbery  Arson  Hurt  Protection of Civil Rights (PCR) Act  \
0        0        0      0     2                                     0   
1        0        0      0     7                                     0   
2        0        0      0     2                                     0   
3        0        0      0     2                                     0   
4        0        0      0     0                                     0   

   Prevention of atrocities (POA) Act  Other Crimes Against STs  
0                                   0                        13  
1                                   1                         6  
2                                   0                         0  
3                                   2                         0  
4                                   0                        14

In [13]:
df3.rename(columns={'STATE/UT': 'State','Kidnapping Abduction': 'Kidnapping and Abduction'}, inplace=True)
df3.head()

State       DISTRICT  Year  Murder  Rape  \
0  ANDHRA PRADESH       ADILABAD  2001       0     1   
1  ANDHRA PRADESH      ANANTAPUR  2001       0     0   
2  ANDHRA PRADESH       CHITTOOR  2001       0     0   
3  ANDHRA PRADESH       CUDDAPAH  2001       0     0   
4  ANDHRA PRADESH  EAST GODAVARI  2001       0     0   

   Kidnapping and Abduction  Dacoity  Robbery  Arson  Hurt  \
0                         2        0        0      0     2   
1                         0        0        0      0     7   
2                         0        0        0      0     2   
3                         0        0        0      0     2   
4                         0        0        0      0     0   

   Protection of Civil Rights (PCR) Act  Prevention of atrocities (POA) Act  \
0                                     0                                   0   
1                                     0                                   1   
2                                     0                                   0   
3                                     0                                   2   
4                                     0                                   0   

   Other Crimes Against STs  
0                        13  
1                         6  
2                         0  
3                         0  
4                        14

In [14]:
df4=pd.read_csv(r'E:\India_Crime - Copy\crime d.csv')
df4

STATE/UT       DISTRICT  Year  Murder  Rape  \
0     ANDHRA PRADESH       ADILABAD  2001     0.0   0.0   
1     ANDHRA PRADESH      ANANTAPUR  2001    19.0  12.0   
2     ANDHRA PRADESH       CHITTOOR  2001     0.0   0.0   
3     ANDHRA PRADESH       CUDDAPAH  2001     0.0   0.0   
4     ANDHRA PRADESH  EAST GODAVARI  2001     0.0   0.0   
...              ...            ...   ...     ...   ...   
9010     LAKSHADWEEP    LAKSHADWEEP  2012     0.0   0.0   
9011     LAKSHADWEEP          TOTAL  2012     0.0   0.0   
9012      PUDUCHERRY       KARAIKAL  2012     0.0   3.0   
9013      PUDUCHERRY     PUDUCHERRY  2012     0.0   4.0   
9014      PUDUCHERRY          TOTAL  2012     0.0   7.0   

      Kidnapping and Abduction  Foeticide  Abetment of suicide  \
0                          0.0        0.0                  0.0   
1                         29.0        0.0                  6.0   
2                          0.0        0.0                  0.0   
3                          0.0        0.0                  0.0   
4                          0.0        0.0                  0.0   
...                        ...        ...                  ...   
9010                       0.0        0.0                  0.0   
9011                       0.0        0.0                  0.0   
9012                       2.0        0.0                  0.0   
9013                      16.0        0.0                  0.0   
9014                      18.0        0.0                  0.0   

      Exposure and abandonment  Procuration of minor girls  \
0                          0.0                         0.0   
1                          0.0                         0.0   
2                          0.0                         0.0   
3                          0.0                         0.0   
4                          0.0                         0.0   
...                        ...                         ...   
9010                       0.0                         0.0   
9011                       0.0                         0.0   
9012                       1.0                         0.0   
9013                       2.0                         0.0   
9014                       3.0                         0.0   

      Buying of girls for prostitution  Selling of girls for prostitution  \
0                                  0.0                                0.0   
1                                  0.0                                0.0   
2                                  0.0                                0.0   
3                                  0.0                                0.0   
4                                  0.0                                0.0   
...                                ...                                ...   
9010                               0.0                                0.0   
9011                               0.0                                0.0   
9012                               0.0                                0.0   
9013                               0.0                                0.0   
9014                               0.0                                0.0   

      Prohibition of child marriage act  Other Crimes  Total  
0                                   0.0           0.0      0  
1                                   0.0           0.0     66  
2                                   0.0           0.0      0  
3                                   0.0           0.0      0  
4                                   0.0           0.0      0  
...                                 ...           ...    ...  
9010                                0.0           0.0      0  
9011                                0.0           0.0      0  
9012                                0.0           1.0      7  
9013                                1.0           2.0     25  
9014                                1.0           3.0     32  

[9015 rows x 15 columns]

In [15]:
df4.drop(['Total'],axis=1,inplace=True)

In [16]:
df4.rename(columns={'STATE/UT': 'State'}, inplace=True)
df4.head()

State       DISTRICT  Year  Murder  Rape  \
0  ANDHRA PRADESH       ADILABAD  2001     0.0   0.0   
1  ANDHRA PRADESH      ANANTAPUR  2001    19.0  12.0   
2  ANDHRA PRADESH       CHITTOOR  2001     0.0   0.0   
3  ANDHRA PRADESH       CUDDAPAH  2001     0.0   0.0   
4  ANDHRA PRADESH  EAST GODAVARI  2001     0.0   0.0   

   Kidnapping and Abduction  Foeticide  Abetment of suicide  \
0                       0.0        0.0                  0.0   
1                      29.0        0.0                  6.0   
2                       0.0        0.0                  0.0   
3                       0.0        0.0                  0.0   
4                       0.0        0.0                  0.0   

   Exposure and abandonment  Procuration of minor girls  \
0                       0.0                         0.0   
1                       0.0                         0.0   
2                       0.0                         0.0   
3                       0.0                         0.0   
4                       0.0                         0.0   

   Buying of girls for prostitution  Selling of girls for prostitution  \
0                               0.0                                0.0   
1                               0.0                                0.0   
2                               0.0                                0.0   
3                               0.0                                0.0   
4                               0.0                                0.0   

   Prohibition of child marriage act  Other Crimes  
0                                0.0           0.0  
1                                0.0           0.0  
2                                0.0           0.0  
3                                0.0           0.0  
4                                0.0           0.0

In [17]:
dataf=pd.concat([df1,df2,df3,df4],axis=0)
dataf

State  Year  Murder  Attempt to murder  \
0     ANDHRA PRADESH  2001   101.0               60.0   
1     ANDHRA PRADESH  2001   151.0              125.0   
2     ANDHRA PRADESH  2001   101.0               57.0   
3     ANDHRA PRADESH  2001    80.0               53.0   
4     ANDHRA PRADESH  2001    82.0               67.0   
...              ...   ...     ...                ...   
9010     LAKSHADWEEP  2012     0.0                NaN   
9011     LAKSHADWEEP  2012     0.0                NaN   
9012      PUDUCHERRY  2012     0.0                NaN   
9013      PUDUCHERRY  2012     0.0                NaN   
9014      PUDUCHERRY  2012     0.0                NaN   

      Culpable homicide not amounting to muder  Rape  \
0                                         17.0  50.0   
1                                          1.0  23.0   
2                                          2.0  27.0   
3                                          1.0  20.0   
4                                          1.0  23.0   
...                                        ...   ...   
9010                                       NaN   0.0   
9011                                       NaN   0.0   
9012                                       NaN   3.0   
9013                                       NaN   4.0   
9014                                       NaN   7.0   

      Kidnapping and Abduction  Dacoity  Preparation and assembly for dacoity  \
0                         46.0      9.0                                   0.0   
1                         53.0      8.0                                   0.0   
2                         59.0      4.0                                   0.0   
3                         25.0      1.0                                   0.0   
4                         49.0      4.0                                   0.0   
...                        ...      ...                                   ...   
9010                       0.0      NaN                                   NaN   
9011                       0.0      NaN                                   NaN   
9012                       2.0      NaN                                   NaN   
9013                      16.0      NaN                                   NaN   
9014                      18.0      NaN                                   NaN   

      Robbery  ...  Other Crimes Against SCs  Other Crimes Against STs  \
0        41.0  ...                       NaN                       NaN   
1        16.0  ...                       NaN                       NaN   
2        14.0  ...                       NaN                       NaN   
3         4.0  ...                       NaN                       NaN   
4        25.0  ...                       NaN                       NaN   
...       ...  ...                       ...                       ...   
9010      NaN  ...                       NaN                       NaN   
9011      NaN  ...                       NaN                       NaN   
9012      NaN  ...                       NaN                       NaN   
9013      NaN  ...                       NaN                       NaN   
9014      NaN  ...                       NaN                       NaN   

      Foeticide  Abetment of suicide  Exposure and abandonment  \
0           NaN                  NaN                       NaN   
1           NaN                  NaN                       NaN   
2           NaN                  NaN                       NaN   
3           NaN                  NaN                       NaN   
4           NaN                  NaN                       NaN   
...         ...                  ...                       ...   
9010        0.0                  0.0                       0.0   
9011        0.0                  0.0                       0.0   
9012        0.0                  0.0                       1.0   
9013        0.0                  0.0                       2.0   
9014        0.0                  0.0                       3.0   

  

In [18]:
dataf.replace(np.nan,0,inplace=True)
dataf

State  Year  Murder  Attempt to murder  \
0     ANDHRA PRADESH  2001   101.0               60.0   
1     ANDHRA PRADESH  2001   151.0              125.0   
2     ANDHRA PRADESH  2001   101.0               57.0   
3     ANDHRA PRADESH  2001    80.0               53.0   
4     ANDHRA PRADESH  2001    82.0               67.0   
...              ...   ...     ...                ...   
9010     LAKSHADWEEP  2012     0.0                0.0   
9011     LAKSHADWEEP  2012     0.0                0.0   
9012      PUDUCHERRY  2012     0.0                0.0   
9013      PUDUCHERRY  2012     0.0                0.0   
9014      PUDUCHERRY  2012     0.0                0.0   

      Culpable homicide not amounting to muder  Rape  \
0                                         17.0  50.0   
1                                          1.0  23.0   
2                                          2.0  27.0   
3                                          1.0  20.0   
4                                          1.0  23.0   
...                                        ...   ...   
9010                                       0.0   0.0   
9011                                       0.0   0.0   
9012                                       0.0   3.0   
9013                                       0.0   4.0   
9014                                       0.0   7.0   

      Kidnapping and Abduction  Dacoity  Preparation and assembly for dacoity  \
0                         46.0      9.0                                   0.0   
1                         53.0      8.0                                   0.0   
2                         59.0      4.0                                   0.0   
3                         25.0      1.0                                   0.0   
4                         49.0      4.0                                   0.0   
...                        ...      ...                                   ...   
9010                       0.0      0.0                                   0.0   
9011                       0.0      0.0                                   0.0   
9012                       2.0      0.0                                   0.0   
9013                      16.0      0.0                                   0.0   
9014                      18.0      0.0                                   0.0   

      Robbery  ...  Other Crimes Against SCs  Other Crimes Against STs  \
0        41.0  ...                       0.0                       0.0   
1        16.0  ...                       0.0                       0.0   
2        14.0  ...                       0.0                       0.0   
3         4.0  ...                       0.0                       0.0   
4        25.0  ...                       0.0                       0.0   
...       ...  ...                       ...                       ...   
9010      0.0  ...                       0.0                       0.0   
9011      0.0  ...                       0.0                       0.0   
9012      0.0  ...                       0.0                       0.0   
9013      0.0  ...                       0.0                       0.0   
9014      0.0  ...                       0.0                       0.0   

      Foeticide  Abetment of suicide  Exposure and abandonment  \
0           0.0                  0.0                       0.0   
1           0.0                  0.0                       0.0   
2           0.0                  0.0                       0.0   
3           0.0                  0.0                       0.0   
4           0.0                  0.0                       0.0   
...         ...                  ...                       ...   
9010        0.0                  0.0                       0.0   
9011        0.0                  0.0                       0.0   
9012        0.0                  0.0                       1.0   
9013        0.0                  0.0                       2.0   
9014        0.0                  0.0                       3.0   

  

In [19]:
df5=pd.read_csv(r'E:\India_Crime - Copy\crime e.csv')
df5

STATE/UT  Year                                     CRIME  \
0      Andhra Pradesh  2001                                    Murder   
1      Andhra Pradesh  2001                  Attempt to Commit Murder   
2      Andhra Pradesh  2001               C H Not amounting to Murder   
3      Andhra Pradesh  2001                                      Rape   
4      Andhra Pradesh  2001                            Custodial Rape   
...               ...   ...                                       ...   
10495      Puducherry  2010           Cruelty by Husband or Relatives   
10496      Puducherry  2010  Importation of girls from Foreign Countr   
10497      Puducherry  2010               Causing death by negligence   
10498      Puducherry  2010                          Other IPC Crimes   
10499      Puducherry  2010                          Total IPC Crimes   

       Boys 7-12 Years  Girls 7-12 Years  Boys 12-16 Years  Girls 12-16 Years  \
0                    3                 0                 7                  0   
1                    2                 0                 0                  0   
2                    0                 0                 0                  0   
3                    2                 0                15                  0   
4                    0                 0                 0                  0   
...                ...               ...               ...                ...   
10495                0                 0                 0                  0   
10496                0                 0                 0                  0   
10497                0                 0                 0                  0   
10498                0                 0                 1                  0   
10499                0                 0                 8                  0   

       Boys 16-18 Years  Girls 16-18 Years  Total for boys all Age Groups  \
0                     5                  0                             15   
1                    11                  0                             13   
2                     0                  0                              0   
3                     2                  1                             19   
4                     0                  0                              0   
...                 ...                ...                            ...   
10495                 0                  0                              0   
10496                 0                  0                              0   
10497                 0                  0                              0   
10498                 2                  3                              3   
10499                31                  4                             39   

       Total for girls all Age Groups  Grand total  
0                                   0           15  
1                                   0           13  
2                                   0            0  
3                                   1           20  
4                                   0            0  
...                               ...          ...  
10495                               0            0  
10496                               0            0  
10497                               0            0  
10498                               3            6  
10499                               4           43  

[10500 rows x 12 columns]

In [20]:
df5.rename(columns={'STATE/UT':'State'}, inplace=True)
df5

State  Year                                     CRIME  \
0      Andhra Pradesh  2001                                    Murder   
1      Andhra Pradesh  2001                  Attempt to Commit Murder   
2      Andhra Pradesh  2001               C H Not amounting to Murder   
3      Andhra Pradesh  2001                                      Rape   
4      Andhra Pradesh  2001                            Custodial Rape   
...               ...   ...                                       ...   
10495      Puducherry  2010           Cruelty by Husband or Relatives   
10496      Puducherry  2010  Importation of girls from Foreign Countr   
10497      Puducherry  2010               Causing death by negligence   
10498      Puducherry  2010                          Other IPC Crimes   
10499      Puducherry  2010                          Total IPC Crimes   

       Boys 7-12 Years  Girls 7-12 Years  Boys 12-16 Years  Girls 12-16 Years  \
0                    3                 0                 7                  0   
1                    2                 0                 0                  0   
2                    0                 0                 0                  0   
3                    2                 0                15                  0   
4                    0                 0                 0                  0   
...                ...               ...               ...                ...   
10495                0                 0                 0                  0   
10496                0                 0                 0                  0   
10497                0                 0                 0                  0   
10498                0                 0                 1                  0   
10499                0                 0                 8                  0   

       Boys 16-18 Years  Girls 16-18 Years  Total for boys all Age Groups  \
0                     5                  0                             15   
1                    11                  0                             13   
2                     0                  0                              0   
3                     2                  1                             19   
4                     0                  0                              0   
...                 ...                ...                            ...   
10495                 0                  0                              0   
10496                 0                  0                              0   
10497                 0                  0                              0   
10498                 2                  3                              3   
10499                31                  4                             39   

       Total for girls all Age Groups  Grand total  
0                                   0           15  
1                                   0           13  
2                                   0            0  
3                                   1           20  
4                                   0            0  
...                               ...          ...  
10495                               0            0  
10496                               0            0  
10497                               0            0  
10498                               3            6  
10499                               4           43  

[10500 rows x 12 columns]

In [21]:
boy=df5.groupby(['State'])['Boys 7-12 Years'].sum().sort_values(ascending=False)
boy

State
Madhya Pradesh       5836
Maharashtra          4967
Chhattisgarh         1773
Andhra Pradesh       1771
Jharkhand            1665
Gujarat              1470
Assam                1286
Rajasthan            1090
Odisha                909
Karnataka             899
Tamil Nadu            738
Delhi UT              683
Mizoram               476
Haryana               353
Punjab                254
West Bengal           227
Chandigarh            173
Goa                   138
Uttarakhand           138
Arunachal Pradesh     136
Bihar                 133
Meghalaya             110
Uttar Pradesh          75
Himachal Pradesh       73
Kerala                 71
Tripura                50
Sikkim                 32
Jammu & Kashmir        31
Nagaland               29
A&N Islands            10
D&N Haveli              5
Puducherry              3
Manipur                 0
Lakshadweep             0
Daman & Diu             0
Name: Boys 7-12 Years, dtype: int64

In [22]:
boys=df5.groupby(['State','CRIME'])['Boys 7-12 Years'].sum().sort_values(ascending=False)
boys

State            CRIME                                   
Madhya Pradesh   Total IPC Crimes                            2712
Maharashtra      Total IPC Crimes                            2015
Madhya Pradesh   Other IPC Crimes                            1120
Maharashtra      Theft                                        928
                 Other Theft                                  842
                                                             ... 
Jammu & Kashmir  Kidnapping & Abduction                         0
                 Preparation & Assembly for Dacoity             0
                 Riots                                          0
                 Robbery                                        0
Kerala           Importation of girls from Foreign Countr       0
Name: Boys 7-12 Years, Length: 1050, dtype: int64

In [23]:
boys_1=df5.groupby(['State'])['Boys 12-16 Years'].sum().sort_values(ascending=False)
boys_1

State
Madhya Pradesh       47670
Maharashtra          45491
Chhattisgarh         20332
Rajasthan            15543
Gujarat              14845
Andhra Pradesh       13683
Haryana               7409
Tamil Nadu            7379
Delhi UT              7106
Odisha                5539
Jharkhand             5245
Assam                 5221
Karnataka             4101
Bihar                 3356
Kerala                3016
Uttar Pradesh         2028
Chandigarh            1434
Arunachal Pradesh     1271
Mizoram               1152
Himachal Pradesh      1072
Punjab                1025
West Bengal            991
Uttarakhand            768
Goa                    666
Meghalaya              631
Puducherry             353
Sikkim                 164
Jammu & Kashmir        162
Tripura                133
A&N Islands            132
D&N Haveli             101
Nagaland                89
Daman & Diu             21
Lakshadweep              2
Manipur                  0
Name: Boys 12-16 Years, dtype: int64

In [24]:
boys1=df5.groupby(['State','CRIME'])['Boys 12-16 Years'].sum().sort_values(ascending=False)
boys1

State           CRIME                                   
Madhya Pradesh  Total IPC Crimes                            22164
Maharashtra     Total IPC Crimes                            19325
Chhattisgarh    Total IPC Crimes                             9188
Madhya Pradesh  Other IPC Crimes                             9068
Rajasthan       Total IPC Crimes                             6830
                                                            ...  
Karnataka       Custodial Rape                                  0
Puducherry      Attempt to Commit Murder                        0
Karnataka       Dowry Deaths                                    0
Puducherry      Arson                                           0
Kerala          Importation of girls from Foreign Countr        0
Name: Boys 12-16 Years, Length: 1050, dtype: int64

In [25]:
boys2=df5.groupby(['State','CRIME'])['Boys 16-18 Years'].sum().sort_values(ascending=False)
boys2

State           CRIME                                   
Madhya Pradesh  Total IPC Crimes                            33442
Maharashtra     Total IPC Crimes                            30174
Madhya Pradesh  Other IPC Crimes                            13713
Rajasthan       Total IPC Crimes                            11692
Gujarat         Total IPC Crimes                            11562
                                                            ...  
Lakshadweep     Rape                                            0
                Preparation & Assembly for Dacoity              0
                Other Theft                                     0
                Other Rape                                      0
Kerala          Importation of girls from Foreign Countr        0
Name: Boys 16-18 Years, Length: 1050, dtype: int64

In [26]:
girls=df5.groupby(['State','CRIME'])['Girls 7-12 Years'].sum().sort_values(ascending=False)
girls

State             CRIME                                   
Madhya Pradesh    Total IPC Crimes                            187
Maharashtra       Total IPC Crimes                            160
Chhattisgarh      Total IPC Crimes                             98
Gujarat           Total IPC Crimes                             80
Madhya Pradesh    Other IPC Crimes                             72
                                                             ... 
Himachal Pradesh  Arson                                         0
                  Assault on Women wih intent to outrage h      0
                  Attempt to Commit Murder                      0
                  Auto Theft                                    0
Kerala            Importation of girls from Foreign Countr      0
Name: Girls 7-12 Years, Length: 1050, dtype: int64

In [27]:
girls1=df5.groupby(['State','CRIME'])['Girls 12-16 Years'].sum().sort_values(ascending=False)
girls1

State             CRIME                                   
Madhya Pradesh    Total IPC Crimes                            1367
Maharashtra       Total IPC Crimes                            1252
Gujarat           Total IPC Crimes                             629
Madhya Pradesh    Other IPC Crimes                             594
                  Hurt/Grevious Hurt                           382
                                                              ... 
Himachal Pradesh  Rape                                           0
                  Robbery                                        0
Jammu & Kashmir   Arson                                          0
                  Assault on Women wih intent to outrage h       0
Kerala            Importation of girls from Foreign Countr       0
Name: Girls 12-16 Years, Length: 1050, dtype: int64

In [28]:
girls2=df5.groupby(['State','CRIME'])['Girls 16-18 Years'].sum().sort_values(ascending=False)
girls2

State            CRIME                                   
Madhya Pradesh   Total IPC Crimes                            2067
Maharashtra      Total IPC Crimes                            1989
Gujarat          Total IPC Crimes                            1198
Rajasthan        Total IPC Crimes                            1067
Madhya Pradesh   Other IPC Crimes                             956
                                                             ... 
Jammu & Kashmir  Dowry Deaths                                   0
                 Hurt/Grevious Hurt                             0
                 Importation of girls from Foreign Countr       0
                 Insult to Modesty of Women                     0
Kerala           Importation of girls from Foreign Countr       0
Name: Girls 16-18 Years, Length: 1050, dtype: int64

In [29]:
t_boy=df5.groupby(['State','CRIME'])['Total for boys all Age Groups'].sum().sort_values(ascending=False)
t_boy

State           CRIME                                   
Madhya Pradesh  Total IPC Crimes                            58318
Maharashtra     Total IPC Crimes                            51514
Madhya Pradesh  Other IPC Crimes                            23901
Rajasthan       Total IPC Crimes                            19004
Gujarat         Total IPC Crimes                            18565
                                                            ...  
Lakshadweep     Dacoity                                         0
                Custodial Rape                                  0
                Cruelty by Husband or Relatives                 0
                Criminal Breach of Trust                        0
Kerala          Importation of girls from Foreign Countr        0
Name: Total for boys all Age Groups, Length: 1050, dtype: int64

In [30]:
t_girl=df5.groupby(['State','CRIME'])['Total for girls all Age Groups'].sum().sort_values(ascending=False)
t_girl

State            CRIME                                   
Madhya Pradesh   Total IPC Crimes                            3621
Maharashtra      Total IPC Crimes                            3401
Gujarat          Total IPC Crimes                            1907
Madhya Pradesh   Other IPC Crimes                            1622
Rajasthan        Total IPC Crimes                            1367
                                                             ... 
Jammu & Kashmir  Insult to Modesty of Women                     0
                 K & A of Women and Girls                       0
                 K & A of others                                0
                 Kidnapping & Abduction                         0
Kerala           Importation of girls from Foreign Countr       0
Name: Total for girls all Age Groups, Length: 1050, dtype: int64

In [31]:
df5.drop(['Boys 7-12 Years','Boys 12-16 Years','Boys 16-18 Years','Girls 7-12 Years','Girls 12-16 Years','Girls 16-18 Years','Grand total'],axis=1,inplace=True)

In [32]:
df5.head()

State  Year                        CRIME  \
0  Andhra Pradesh  2001                       Murder   
1  Andhra Pradesh  2001     Attempt to Commit Murder   
2  Andhra Pradesh  2001  C H Not amounting to Murder   
3  Andhra Pradesh  2001                         Rape   
4  Andhra Pradesh  2001               Custodial Rape   

   Total for boys all Age Groups  Total for girls all Age Groups  
0                             15                               0  
1                             13                               0  
2                              0                               0  
3                             19                               1  
4                              0                               0

In [33]:
df6=pd.read_csv(r'E:\India_Crime - Copy\crime f.csv')
df6.head()

Area_Name  Year         Group_Name Sub_Group_Name  \
0  Andaman & Nicobar Islands  2001  Cattle - Property      2. Cattle   
1             Andhra Pradesh  2001  Cattle - Property      2. Cattle   
2          Arunachal Pradesh  2001  Cattle - Property      2. Cattle   
3                      Assam  2001  Cattle - Property      2. Cattle   
4                      Bihar  2001  Cattle - Property      2. Cattle   

   Cases_Property_Recovered  Cases_Property_Stolen  \
0                         0                      1   
1                       448                    580   
2                        22                     34   
3                       149                    322   
4                       144                    334   

   Value_of_Property_Recovered  Value_of_Property_Stolen  
0                            0                      1000  
1                      6490596                   7233876  
2                       135500                    704500  
3                       683350                   1816386  
4                       896019                   1911068

In [34]:
df6.Sub_Group_Name.unique()

array(['2. Cattle', '1. Communation and Electricity Wire',
       '8. Cultural Property including Antiques', '3. Cycle',
       '7. Electronic Components', '5. Fire Arms',
       '6. Explosives/Explosive Substances',
       '4.2 Motor Vehicles - Motor Car/Taxi/Jeep',
       '4.3 Motor Vehicles - Other Motor Vehicles', '4. Motor Vehicles',
       '4.1 Motor Vehicles - Motor Cycle/Scooters',
       '9. Other kinds of Property', 'Total Property Stolen & Recovered'],
      dtype=object)

In [35]:
df6.drop(['Sub_Group_Name'],axis=1,inplace=True)

In [36]:
df6.rename(columns={'Area_Name':'State'},inplace=True)

In [37]:
df6.head()

State  Year         Group_Name  \
0  Andaman & Nicobar Islands  2001  Cattle - Property   
1             Andhra Pradesh  2001  Cattle - Property   
2          Arunachal Pradesh  2001  Cattle - Property   
3                      Assam  2001  Cattle - Property   
4                      Bihar  2001  Cattle - Property   

   Cases_Property_Recovered  Cases_Property_Stolen  \
0                         0                      1   
1                       448                    580   
2                        22                     34   
3                       149                    322   
4                       144                    334   

   Value_of_Property_Recovered  Value_of_Property_Stolen  
0                            0                      1000  
1                      6490596                   7233876  
2                       135500                    704500  
3                       683350                   1816386  
4                       896019                   1911068

In [38]:
recover=df6.groupby(['State','Group_Name'])['Cases_Property_Recovered'].sum().sort_values(ascending=False)
recover

State             Group_Name                        
Maharashtra       Total Property(Nature)                236593
                  Other Nature of Property              186262
Tamil Nadu        Total Property(Nature)                171074
Andhra Pradesh    Total Property(Nature)                166255
Madhya Pradesh    Total Property(Nature)                127053
                                                         ...  
Uttar Pradesh     Motor Vehicles - Property                  0
Goa               Motor Vehicles - Property                  0
Daman & Diu       Motor Vehicles - Property                  0
                  Motor Vehicles - Others - Property         0
Himachal Pradesh  Motor Vehicles - Property                  0
Name: Cases_Property_Recovered, Length: 420, dtype: int64

In [39]:
state=df6.groupby(['State'])['Cases_Property_Recovered'].sum().sort_values(ascending=False)
state

State
Maharashtra                  515253
Tamil Nadu                   374758
Andhra Pradesh               365664
Madhya Pradesh               278003
Uttar Pradesh                194531
Gujarat                      189343
Delhi                        185183
Karnataka                    181709
Haryana                      160311
Rajasthan                    159169
Odisha                       109710
Punjab                        94791
West Bengal                   92953
Kerala                        81294
Chhattisgarh                  75361
Bihar                         67602
Assam                         58574
Jharkhand                     38247
Jammu & Kashmir               25424
Mizoram                       19371
Chandigarh                    18449
Uttarakhand                   16353
Himachal Pradesh              11503
Puducherry                     8798
Goa                            6706
Arunachal Pradesh              6404
Meghalaya                      4286
Tripura               

In [40]:
g_name=df6.groupby(['Group_Name'])['Cases_Property_Recovered'].sum().sort_values(ascending=False)
g_name

Group_Name
Total Property(Nature)                                1509678
Other Nature of Property                              1041726
Fire arms - Property                                   540174
Cycle - Property                                        64631
Motor Vehicles - Motor car/Taxi/Jeep - Property         48911
Electronic Components - Property                        39660
Cattle - Property                                       38957
Communication and Electricity Wire - Property           38741
Cultural Property including Antiques - Property         22918
Motor Vehicles - Others - Property                       4394
Motor Vehicles -\tMotor Cycles/Scooters - Property       1762
Motor Vehicles - Property                                 469
Name: Cases_Property_Recovered, dtype: int64

In [41]:
stolen=df6.groupby(['Group_Name'])['Cases_Property_Stolen'].sum().sort_values(ascending=False)
stolen

Group_Name
Total Property(Nature)                                4187094
Other Nature of Property                              2803596
Fire arms - Property                                  1904740
Electronic Components - Property                       156525
Motor Vehicles - Motor car/Taxi/Jeep - Property        124375
Communication and Electricity Wire - Property          110537
Cycle - Property                                       106790
Cattle - Property                                       67990
Cultural Property including Antiques - Property         55408
Motor Vehicles - Others - Property                      14460
Motor Vehicles -\tMotor Cycles/Scooters - Property       5667
Motor Vehicles - Property                                1309
Name: Cases_Property_Stolen, dtype: int64

In [42]:
state=df6.groupby(['State'])['Cases_Property_Stolen'].sum().sort_values(ascending=False)
state

State
Maharashtra                  1535782
Madhya Pradesh                819819
Andhra Pradesh                707653
Uttar Pradesh                 672276
Delhi                         635795
Gujarat                       622993
Karnataka                     570524
Rajasthan                     557767
Tamil Nadu                    476573
Bihar                         437835
West Bengal                   405243
Haryana                       380353
Assam                         260312
Kerala                        246847
Odisha                        242469
Chhattisgarh                  218707
Jharkhand                     192610
Punjab                        175301
Jammu & Kashmir                84564
Chandigarh                     50266
Uttarakhand                    48127
Himachal Pradesh               37781
Mizoram                        27498
Goa                            22274
Meghalaya                      18543
Puducherry                     17909
Arunachal Pradesh              1

In [43]:
p_recover=df6.groupby(['Group_Name'])['Value_of_Property_Recovered'].sum().sort_values(ascending=False)
p_recover

Group_Name
Total Property(Nature)                                71754803608
Other Nature of Property                              47804264248
Fire arms - Property                                  39166897394
Electronic Components - Property                       7612693002
Cultural Property including Antiques - Property        5475419771
Motor Vehicles - Others - Property                     1473677010
Motor Vehicles - Motor car/Taxi/Jeep - Property        1470620510
Communication and Electricity Wire - Property           658381248
Cattle - Property                                       560644382
Cycle - Property                                        113233522
Motor Vehicles -\tMotor Cycles/Scooters - Property       78982844
Motor Vehicles - Property                                11551147
Name: Value_of_Property_Recovered, dtype: int64

In [44]:
p_recover1=df6.groupby(['State'])['Value_of_Property_Recovered'].sum().sort_values(ascending=False)
p_recover1

State
Maharashtra                  29543342881
Madhya Pradesh               22427531681
Uttar Pradesh                16116759792
Rajasthan                    14614007333
Haryana                      12157629227
Karnataka                    11079496779
Tamil Nadu                   10628122452
Andhra Pradesh               10042202784
Punjab                       10005401525
Gujarat                       8409192128
West Bengal                   5822200089
Kerala                        4023466295
Delhi                         3822400256
Odisha                        3143069274
Chhattisgarh                  2450294352
Assam                         2050088094
Jammu & Kashmir               1717500732
Bihar                         1444176791
Himachal Pradesh              1057496786
Chandigarh                     946569182
Jharkhand                      851682603
Uttarakhand                    683096234
Arunachal Pradesh              676669714
Goa                            440225856
Mizoram   

In [45]:
p_stole1=df6.groupby(['State'])['Value_of_Property_Stolen'].sum().sort_values(ascending=False)
p_stole1

State
Maharashtra                  217063089987
Delhi                         74497210284
Gujarat                       71285745744
Madhya Pradesh                35554532139
Karnataka                     33945698679
Kerala                        30857528237
Uttar Pradesh                 29094427241
Rajasthan                     25739605450
West Bengal                   25543386953
Andhra Pradesh                21583696194
Haryana                       20544901951
Punjab                        18625442713
Tamil Nadu                    16270244954
Odisha                        14063656181
Bihar                          9295129888
Assam                          7426993931
Chhattisgarh                   6912572828
Jharkhand                      5468354472
Nagaland                       4783250928
Goa                            4400660150
Jammu & Kashmir                4032599465
Himachal Pradesh               3593845347
Chandigarh                     2615635654
Uttarakhand                 

In [46]:
p_stole=df6.groupby(['Group_Name'])['Value_of_Property_Stolen'].sum().sort_values(ascending=False)
p_stole

Group_Name
Total Property(Nature)                                301892443242
Other Nature of Property                              235466395878
Fire arms - Property                                  111251909252
Electronic Components - Property                       23379282453
Cultural Property including Antiques - Property        13934984432
Motor Vehicles - Motor car/Taxi/Jeep - Property         5298274631
Communication and Electricity Wire - Property           2300024694
Motor Vehicles - Others - Property                      1798635308
Cattle - Property                                        969885432
Motor Vehicles -\tMotor Cycles/Scooters - Property       226823902
Cycle - Property                                         180362213
Motor Vehicles - Property                                 26086558
Name: Value_of_Property_Stolen, dtype: int64

In [47]:
df7=pd.read_csv(r'E:\India_Crime - Copy\crime g.csv')
df7

Area_Name  Year                         Group_Name  \
0     Andaman & Nicobar Islands  2001  Police - Assistant Sub-Inspectors   
1                Andhra Pradesh  2001  Police - Assistant Sub-Inspectors   
2             Arunachal Pradesh  2001  Police - Assistant Sub-Inspectors   
3                         Assam  2001  Police - Assistant Sub-Inspectors   
4                         Bihar  2001  Police - Assistant Sub-Inspectors   
...                         ...   ...                                ...   
2445                 Tamil Nadu  2010                     Police - Total   
2446                    Tripura  2010                     Police - Total   
2447              Uttar Pradesh  2010                     Police - Total   
2448                Uttarakhand  2010                     Police - Total   
2449                West Bengal  2010                     Police - Total   

                         Sub_Group_Name  Police_Injured_By_Criminals  \
0            3. Assistant Sub-Inspectos                            0   
1            3. Assistant Sub-Inspectos                            0   
2            3. Assistant Sub-Inspectos                            0   
3            3. Assistant Sub-Inspectos                            0   
4            3. Assistant Sub-Inspectos                            1   
...                                 ...                          ...   
2445  7. Total Police Killed or Injured                           10   
2446  7. Total Police Killed or Injured                            0   
2447  7. Total Police Killed or Injured                            6   
2448  7. Total Police Killed or Injured                            0   
2449  7. Total Police Killed or Injured                           17   

      Police_Injured_By_Riotous_Mobs  Police_Injured_In_Accidents  \
0                                  0                            0   
1                                  3                            4   
2                                  0                            0   
3                                  0                            0   
4                                  0                            0   
...                              ...                          ...   
2445                              26                          142   
2446                               0                            0   
2447                              10                            9   
2448                               0                            5   
2449                             265                           86   

      Police_Injured_In_Dacoity_OperationsOther_raids  \
0                                                   0   
1                                                   1   
2                                                   0   
3                                                   0   
4                                                   0   
...                                               ...   
2445                                                4   
2446                                                0   
2447                                               10   
2448                                                0   
2449                                               23   

      Police_Injured_In_TerroristsExtremists_Operations  \
0                                                     0   
1                                                     3   
2                                                     0   
3                                                     1   
4                                                     2   
...                                                 ...   
2445                                                  0   
2446                                                  2   
2447                                                  0   
2448                                                  0   
2449                                                 21   

      Police_Injured_

In [48]:
df7.drop(['Sub_Group_Name','Police_Injured_By_Criminals','Police_Injured_By_Riotous_Mobs','Police_Injured_In_Accidents','Police_Injured_In_Dacoity_OperationsOther_raids','Police_Injured_In_TerroristsExtremists_Operations','Police_Injured_On_Border_Duties','Police_Killed_By_Criminals','Police_Killed_By_Riotous_Mobs','Police_Killed_In_Accidents','Police_Killed_In_Dacoity_OperationsOther_raids','Police_Killed_In_TerroristsExtremists_Operations','Police_Killed_On_Border_Duties'],axis=1,inplace=True)

In [49]:
df7.rename(columns={'Area_Name':'State'},inplace=True)

In [50]:
df8=pd.read_csv(r'E:\India_Crime - Copy\crime h.csv')
df8

STATE/UT  YEAR         Place Of Occurrence  \
0     Andhra Pradesh  2001        RESIDENTIAL PREMISES   
1     Andhra Pradesh  2001                    HIGH-WAY   
2     Andhra Pradesh  2001                 RIVER & SEA   
3     Andhra Pradesh  2001                    RAILWAYS   
4     Andhra Pradesh  2001              RUNNING TRAINS   
...              ...   ...                         ...   
4339      Puducherry  2012                       BANKS   
4340      Puducherry  2012   COMMERCIAL ESTABLISHMENTS   
4341      Puducherry  2012                OTHER PLACES   
4342      Puducherry  2012              TOTAL (MANUAL)   
4343      Puducherry  2012  TOTAL COMPUTER FROM 1 TO 7   

      Dacoity (Section 395-398 IPC) - Number of cases registered  \
0                                                   100            
1                                                    57            
2                                                     2            
3                                                     8            
4                                                     5            
...                                                 ...            
4339                                                  0            
4340                                                  2            
4341                                                  2            
4342                                                  5            
4343                                                  5            

      Dacoity (Section 395-398 IPC) - Value Of Property Stolen (in rupees)  \
0                                               4446961                      
1                                               5340335                      
2                                                145345                      
3                                               1750800                      
4                                                 75000                      
...                                                 ...                      
4339                                                  0                      
4340                                              58000                      
4341                                             575000                      
4342                                             683000                      
4343                                             683000                      

      Robbery(Section 392-394, 397, 398 IPC) - Number of cases registered  \
0                                                   177                     
1                                                   172                     
2                                                    11                     
3                                                    19                     
4                                                     3                     
...                                                 ...                     
4339                                                  0                     
4340                                                  4                     
4341                                                  8                     
4342                                                 16                     
4343                                                 16                     

      Robbery(Section 392-394, 397, 398 IPC) - Value Of Property Stolen (in rupees)  \
0                                               5962460                               
1                                               6364866                               
2                                                209330                               
3                                                304336                               
4                                                164000                               
...                                                 ...                               
4339                       

In [51]:
df8.rename(columns={'STATE/UT':'State','YEAR':'Year'},inplace=True)

In [52]:
df9=pd.read_csv(r'E:\India_Crime - Copy\crime i.csv')
df9

STATE/UT  YEAR  RESIDENTIAL PREMISES - Dacoity  \
0       ANDHRA PRADESH  2001                             100   
1    ARUNACHAL PRADESH  2001                               9   
2                ASSAM  2001                             381   
3                BIHAR  2001                             818   
4         CHHATTISGARH  2001                              54   
..                 ...   ...                             ...   
451              DELHI  2012                              10   
452        LAKSHADWEEP  2012                               0   
453         PUDUCHERRY  2012                               1   
454        TOTAL (UTs)  2012                              11   
455  TOTAL (ALL-INDIA)  2012                            1288   

     RESIDENTIAL PREMISES - Robbery  RESIDENTIAL PREMISES - Burglary  \
0                               177                             5158   
1                                26                               99   
2                               191                             1695   
3                               326                             2486   
4                                42                             3336   
..                              ...                              ...   
451                             101                             1249   
452                               0                                3   
453                               4                               47   
454                             123                             1515   
455                            2821                            60698   

     RESIDENTIAL PREMISES - Theft  HIGHWAYS - Dacoity  HIGHWAYS - Robbery  \
0                            4257                  57                 172   
1                             131                   0                   0   
2                            2901                  46                 136   
3                            4741                 162                 826   
4                            1417                  10                  38   
..                            ...                 ...                 ...   
451                          7076                   1                  32   
452                             7                   0                   0   
453                            42                   0                   0   
454                          7974                   1                  32   
455                         81861                 838                5000   

     HIGHWAYS - Burglary  HIGHWAYS - Theft  ...  \
0                     31                74  ...   
1                      0                 8  ...   
2                      7                87  ...   
3                      0               257  ...   
4                     12                72  ...   
..                   ...               ...  ...   
451                    0               189  ...   
452                    0                 0  ...   
453                    0                 0  ...   
454                    0               199  ...   
455                  316             27802  ...   

     COMMERCIAL ESTABLISHMENTS - Burglary  COMMERCIAL ESTABLISHMENTS - Theft  \
0                                    1041                               2502   
1                                      84                                 54   
2                                     442                                967   
3                                     231                                686   
4                                     370                                299   
..                                    ...                                ...   
451                                   285                               1370   
452                                     0                                  0   
453                                    26                                 20   
454                                   412 

In [53]:
df9.drop(['RESIDENTIAL PREMISES - Dacoity','RESIDENTIAL PREMISES - Robbery','RESIDENTIAL PREMISES - Burglary','RESIDENTIAL PREMISES - Theft','HIGHWAYS - Dacoity','HIGHWAYS - Robbery','HIGHWAYS - Burglary','HIGHWAYS - Theft','RIVER and SEA - Dacoity','RIVER and SEA - Robbery','RIVER and SEA - Burglary','RIVER and SEA - Theft','RAILWAYS - Dacoity','RAILWAYS - Robbery','RAILWAYS - Burglary','RAILWAYS - Theft','BANKS - Dacoity','BANKS - Robbery','BANKS - Burglary','BANKS - Theft','COMMERCIAL ESTABLISHMENTS - Dacoity','COMMERCIAL ESTABLISHMENTS - Robbery','COMMERCIAL ESTABLISHMENTS - Burglary','COMMERCIAL ESTABLISHMENTS - Theft','OTHER PLACES - Dacoity','OTHER PLACES - Robbery','OTHER PLACES - Burglary','OTHER PLACES - Theft'],axis=1,inplace=True)

In [54]:
df9.rename(columns={'STATE/UT':'State','YEAR':'Year'},inplace=True)

In [55]:
df10=pd.read_csv(r'E:\India_Crime - Copy\crime j.csv')
df10

Area_Name  Year                     Group_Name  \
0        Andhra Pradesh  2001    HR_Disappearance of Persons   
1     Arunachal Pradesh  2001    HR_Disappearance of Persons   
2                 Assam  2001    HR_Disappearance of Persons   
3                 Bihar  2001    HR_Disappearance of Persons   
4            Chandigarh  2001    HR_Disappearance of Persons   
...                 ...   ...                            ...   
2262          Meghalaya  2010  HR_Total Violations by Police   
2263           Nagaland  2010  HR_Total Violations by Police   
2264             Odisha  2010  HR_Total Violations by Police   
2265      Uttar Pradesh  2010  HR_Total Violations by Police   
2266        West Bengal  2010  HR_Total Violations by Police   

                     Sub_Group_Name  \
0      01. Disappearance of Persons   
1      01. Disappearance of Persons   
2      01. Disappearance of Persons   
3      01. Disappearance of Persons   
4      01. Disappearance of Persons   
...                             ...   
2262  12. Total (Sum of 1-11 Above)   
2263  12. Total (Sum of 1-11 Above)   
2264  12. Total (Sum of 1-11 Above)   
2265  12. Total (Sum of 1-11 Above)   
2266  12. Total (Sum of 1-11 Above)   

      Cases_Registered_under_Human_Rights_Violations  Policemen_Chargesheeted  \
0                                                0.0                      0.0   
1                                                0.0                      0.0   
2                                                0.0                      0.0   
3                                                0.0                      0.0   
4                                                0.0                      0.0   
...                                              ...                      ...   
2262                                             0.0                      0.0   
2263                                             0.0                      0.0   
2264                                             5.0                      1.0   
2265                                             6.0                      5.0   
2266                                             1.0                      0.0   

      Policemen_Convicted  
0                     0.0  
1                     0.0  
2                     0.0  
3                     0.0  
4                     0.0  
...                   ...  
2262                  0.0  
2263                  0.0  
2264                  0.0  
2265                  0.0  
2266                  0.0  

[2267 rows x 7 columns]

In [56]:
df10.drop(['Sub_Group_Name'],axis=1,inplace=True)

In [57]:
df10.rename(columns={'Area_Name':'State'},inplace=True)

In [58]:
df11=pd.read_csv(r'E:\India_Crime - Copy\crime k.csv')
df11

STATE/UT       DISTRICT  Year  Rape  Kidnapping and Abduction  \
0     ANDHRA PRADESH       ADILABAD  2001    50                        30   
1     ANDHRA PRADESH      ANANTAPUR  2001    23                        30   
2     ANDHRA PRADESH       CHITTOOR  2001    27                        34   
3     ANDHRA PRADESH       CUDDAPAH  2001    20                        20   
4     ANDHRA PRADESH  EAST GODAVARI  2001    23                        26   
...              ...            ...   ...   ...                       ...   
9012     LAKSHADWEEP    LAKSHADWEEP  2012     0                         0   
9013     LAKSHADWEEP          TOTAL  2012     0                         0   
9014      PUDUCHERRY       KARAIKAL  2012     6                         2   
9015      PUDUCHERRY     PUDUCHERRY  2012     7                        14   
9016      PUDUCHERRY          TOTAL  2012    13                        16   

      Dowry Deaths  Assault on women with intent to outrage her modesty  \
0               16                                                149     
1                7                                                118     
2               14                                                112     
3               17                                                126     
4               12                                                109     
...            ...                                                ...     
9012             0                                                  1     
9013             0                                                  1     
9014             0                                                  2     
9015             0                                                  7     
9016             0                                                  9     

      Insult to modesty of Women  Cruelty by Husband or his Relatives  \
0                             34                                  175   
1                             24                                  154   
2                             83                                  186   
3                             38                                   57   
4                             58                                  247   
...                          ...                                  ...   
9012                           0                                    1   
9013                           0                                    1   
9014                           0                                    1   
9015                           2                                    5   
9016                           2                                    6   

      Importation of Girls  
0                        0  
1                        0  
2                        0  
3                        0  
4                        0  
...                    ...  
9012                     0  
9013                     0  
9014                     0  
9015                     0  
9016                     0  

[9017 rows x 10 columns]

In [59]:
df11.rename(columns={'STATE/UT': 'State'}, inplace=True)
df11.head()

State       DISTRICT  Year  Rape  Kidnapping and Abduction  \
0  ANDHRA PRADESH       ADILABAD  2001    50                        30   
1  ANDHRA PRADESH      ANANTAPUR  2001    23                        30   
2  ANDHRA PRADESH       CHITTOOR  2001    27                        34   
3  ANDHRA PRADESH       CUDDAPAH  2001    20                        20   
4  ANDHRA PRADESH  EAST GODAVARI  2001    23                        26   

   Dowry Deaths  Assault on women with intent to outrage her modesty  \
0            16                                                149     
1             7                                                118     
2            14                                                112     
3            17                                                126     
4            12                                                109     

   Insult to modesty of Women  Cruelty by Husband or his Relatives  \
0                          34                                  175   
1                          24                                  154   
2                          83                                  186   
3                          38                                   57   
4                          58                                  247   

   Importation of Girls  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0

In [60]:
dataframe=pd.concat([dataf,df5,df6,df7,df8,df9,df10,df11],axis=0)
dataframe

State  Year  Murder  Attempt to murder  \
0     ANDHRA PRADESH  2001   101.0               60.0   
1     ANDHRA PRADESH  2001   151.0              125.0   
2     ANDHRA PRADESH  2001   101.0               57.0   
3     ANDHRA PRADESH  2001    80.0               53.0   
4     ANDHRA PRADESH  2001    82.0               67.0   
...              ...   ...     ...                ...   
9012     LAKSHADWEEP  2012     NaN                NaN   
9013     LAKSHADWEEP  2012     NaN                NaN   
9014      PUDUCHERRY  2012     NaN                NaN   
9015      PUDUCHERRY  2012     NaN                NaN   
9016      PUDUCHERRY  2012     NaN                NaN   

      Culpable homicide not amounting to muder  Rape  \
0                                         17.0  50.0   
1                                          1.0  23.0   
2                                          2.0  27.0   
3                                          1.0  20.0   
4                                          1.0  23.0   
...                                        ...   ...   
9012                                       NaN   0.0   
9013                                       NaN   0.0   
9014                                       NaN   6.0   
9015                                       NaN   7.0   
9016                                       NaN  13.0   

      Kidnapping and Abduction  Dacoity  Preparation and assembly for dacoity  \
0                         46.0      9.0                                   0.0   
1                         53.0      8.0                                   0.0   
2                         59.0      4.0                                   0.0   
3                         25.0      1.0                                   0.0   
4                         49.0      4.0                                   0.0   
...                        ...      ...                                   ...   
9012                       0.0      NaN                                   NaN   
9013                       0.0      NaN                                   NaN   
9014                       2.0      NaN                                   NaN   
9015                      14.0      NaN                                   NaN   
9016                      16.0      NaN                                   NaN   

      Robbery  ...  \
0        41.0  ...   
1        16.0  ...   
2        14.0  ...   
3         4.0  ...   
4        25.0  ...   
...       ...  ...   
9012      NaN  ...   
9013      NaN  ...   
9014      NaN  ...   
9015      NaN  ...   
9016      NaN  ...   

      Burglary(Section 449-452, 454, 455, 457-460 IPC) - Value Of Property Stolen (in rupees)  \
0                                                   NaN                                         
1                                                   NaN                                         
2                                                   NaN                                         
3                                                   NaN                                         
4                                                   NaN                                         
...                                                 ...                                         
9012                                                NaN                                         
9013                                                NaN                                         
9014                                                NaN                                         
9015                                                NaN                                         
9016                                                NaN                                         

      Theft (Section 379-382 IPC) - Number of cases registered  \
0                                                   NaN          
1                                                   NaN          
2                                                   NaN 

In [61]:
dataframe.fillna(0,inplace=True)

In [62]:
dataframe

State  Year  Murder  Attempt to murder  \
0     ANDHRA PRADESH  2001   101.0               60.0   
1     ANDHRA PRADESH  2001   151.0              125.0   
2     ANDHRA PRADESH  2001   101.0               57.0   
3     ANDHRA PRADESH  2001    80.0               53.0   
4     ANDHRA PRADESH  2001    82.0               67.0   
...              ...   ...     ...                ...   
9012     LAKSHADWEEP  2012     0.0                0.0   
9013     LAKSHADWEEP  2012     0.0                0.0   
9014      PUDUCHERRY  2012     0.0                0.0   
9015      PUDUCHERRY  2012     0.0                0.0   
9016      PUDUCHERRY  2012     0.0                0.0   

      Culpable homicide not amounting to muder  Rape  \
0                                         17.0  50.0   
1                                          1.0  23.0   
2                                          2.0  27.0   
3                                          1.0  20.0   
4                                          1.0  23.0   
...                                        ...   ...   
9012                                       0.0   0.0   
9013                                       0.0   0.0   
9014                                       0.0   6.0   
9015                                       0.0   7.0   
9016                                       0.0  13.0   

      Kidnapping and Abduction  Dacoity  Preparation and assembly for dacoity  \
0                         46.0      9.0                                   0.0   
1                         53.0      8.0                                   0.0   
2                         59.0      4.0                                   0.0   
3                         25.0      1.0                                   0.0   
4                         49.0      4.0                                   0.0   
...                        ...      ...                                   ...   
9012                       0.0      0.0                                   0.0   
9013                       0.0      0.0                                   0.0   
9014                       2.0      0.0                                   0.0   
9015                      14.0      0.0                                   0.0   
9016                      16.0      0.0                                   0.0   

      Robbery  ...  \
0        41.0  ...   
1        16.0  ...   
2        14.0  ...   
3         4.0  ...   
4        25.0  ...   
...       ...  ...   
9012      0.0  ...   
9013      0.0  ...   
9014      0.0  ...   
9015      0.0  ...   
9016      0.0  ...   

      Burglary(Section 449-452, 454, 455, 457-460 IPC) - Value Of Property Stolen (in rupees)  \
0                                                   0.0                                         
1                                                   0.0                                         
2                                                   0.0                                         
3                                                   0.0                                         
4                                                   0.0                                         
...                                                 ...                                         
9012                                                0.0                                         
9013                                                0.0                                         
9014                                                0.0                                         
9015                                                0.0                                         
9016                                                0.0                                         

      Theft (Section 379-382 IPC) - Number of cases registered  \
0                                                   0.0          
1                                                   0.0          
2                                                   0.0 

In [63]:
dataframe.columns

Index(['State', 'Year', 'Murder', 'Attempt to murder',
       'Culpable homicide not amounting to muder', 'Rape',
       'Kidnapping and Abduction', 'Dacoity',
       'Preparation and assembly for dacoity', 'Robbery', 'Burglary', 'Theft',
       'Riots', 'CRIMINAL BREACH OF TRUST', 'Cheating', 'COUNTERFIETING',
       'Arson', 'Hurt', 'Dowry Deaths',
       'Assault on women with intent to outrage her modesty',
       'Insult to modesty of Women', 'Cruelty by Husband or his Relatives',
       'Importation of Girls', 'Causing death by negligence',
       'OTHER IPC CRIMES', 'TOTAL IPC CRIMES', 'DISTRICT',
       'Prevention of atrocities (POA) Act',
       'Protection of Civil Rights (PCR) Act', 'Other Crimes Against SCs',
       'Other Crimes Against STs', 'Foeticide', 'Abetment of suicide',
       'Exposure and abandonment', 'Procuration of minor girls',
       'Buying of girls for prostitution', 'Selling of girls for prostitution',
       'Prohibition of child marriage act', 'Other C

In [64]:
df = pd.merge(dataframe, data, on="State",how='outer')
df

State    Year  Murder  Attempt to murder  \
0                   ANDHRA PRADESH  2001.0   101.0               60.0   
1                   ANDHRA PRADESH  2001.0   151.0              125.0   
2                   ANDHRA PRADESH  2001.0   101.0               57.0   
3                   ANDHRA PRADESH  2001.0    80.0               53.0   
4                   ANDHRA PRADESH  2001.0    82.0               67.0   
...                            ...     ...     ...                ...   
69658                        DELHI     NaN     NaN                NaN   
69659            JAMMU AND KASHMIR     NaN     NaN                NaN   
69660  ANDAMAN AND NICOBAR ISLANDS     NaN     NaN                NaN   
69661       DADRA AND NAGAR HAVELI     NaN     NaN                NaN   
69662                DAMAN AND DIU     NaN     NaN                NaN   

       Culpable homicide not amounting to muder  Rape  \
0                                          17.0  50.0   
1                                           1.0  23.0   
2                                           2.0  27.0   
3                                           1.0  20.0   
4                                           1.0  23.0   
...                                         ...   ...   
69658                                       NaN   NaN   
69659                                       NaN   NaN   
69660                                       NaN   NaN   
69661                                       NaN   NaN   
69662                                       NaN   NaN   

       Kidnapping and Abduction  Dacoity  \
0                          46.0      9.0   
1                          53.0      8.0   
2                          59.0      4.0   
3                          25.0      1.0   
4                          49.0      4.0   
...                         ...      ...   
69658                       NaN      NaN   
69659                       NaN      NaN   
69660                       NaN      NaN   
69661                       NaN      NaN   
69662                       NaN      NaN   

       Preparation and assembly for dacoity  Robbery  ...  TOTAL - Dacoity  \
0                                       0.0     41.0  ...              0.0   
1                                       0.0     16.0  ...              0.0   
2                                       0.0     14.0  ...              0.0   
3                                       0.0      4.0  ...              0.0   
4                                       0.0     25.0  ...              0.0   
...                                     ...      ...  ...              ...   
69658                                   NaN      NaN  ...              NaN   
69659                                   NaN      NaN  ...              NaN   
69660                                   NaN      NaN  ...              NaN   
69661                                   NaN      NaN  ...              NaN   
69662                                   NaN      NaN  ...              NaN   

       TOTAL - Robbery  TOTAL - Burglary  TOTAL - Theft  \
0                  0.0               0.0            0.0   
1                  0.0               0.0            0.0   
2                  0.0               0.0            0.0   
3                  0.0               0.0            0.0   
4                  0.0               0.0            0.0   
...                ...               ...            ...   
69658              NaN               NaN            NaN   
69659              NaN               NaN            NaN   
69660              NaN               NaN            NaN   
69661              NaN               NaN            NaN   
69662              NaN               NaN            NaN   

       Cases_Registered_under_Human_Rights_Violations  \
0                                                 0.0   
1                                                 0.0   
2                                                 0.0   
3                                                 0.0   
4      

In [65]:
df.fillna(0,inplace=True)

2.1	Analysis of Literacy Rate vs Total Crimes.

In [66]:
literacy=df.groupby(['State'])['Literacy'].sum().sort_values(ascending=False)
literacy[:30]

State
UTTAR PRADESH                  297927.36
MAHARASHTRA                    228246.48
MADHYA PRADESH                 218496.64
TAMIL NADU                     188772.13
KARNATAKA                      151247.52
GUJARAT                        150753.96
ASSAM                          131457.99
ANDHRA PRADESH                 124791.24
PUNJAB                         119978.88
KERALA                         110638.00
CHHATTISGARH                    94104.92
HIMACHAL PRADESH                73857.60
UTTARAKHAND                     67154.64
ARUNACHAL PRADESH               64530.06
NAGALAND                        56082.75
MIZORAM                         50414.16
MANIPUR                         49010.78
MEGHALAYA                       36619.56
TRIPURA                         30178.12
SIKKIM                          25403.04
GOA                             17030.40
PUDUCHERRY                      14336.95
LAKSHADWEEP                     12124.20
CHANDIGARH                      11358.60
DAMAN AND 

In [67]:
df['TotalCrime']=df['Murder']+df['Attempt to murder']+df['Culpable homicide not amounting to muder']+df['Rape']+df['Kidnapping and Abduction']+df['Dacoity']+df['Preparation and assembly for dacoity']+df['Robbery']+df['Burglary']+df['Theft']+df['Riots']+df['CRIMINAL BREACH OF TRUST']+df['Cheating']+df['COUNTERFIETING']+df['Arson']+df['Hurt']+df['Dowry Deaths']+df['Assault on women with intent to outrage her modesty']+df['Insult to modesty of Women']+df['Cruelty by Husband or his Relatives']+df['Importation of Girls']+df['OTHER IPC CRIMES']+df['TOTAL IPC CRIMES']+df['Other Crimes Against SCs']+df['Foeticide']+df['Exposure and abandonment']+df['Procuration of minor girls']+df['Buying of girls for prostitution']+df['Selling of girls for prostitution']+df['Other Crimes Against STs']+df['Abetment of suicide']+df['Causing death by negligence']+df['Other Crimes']+df['Police_Injured_Total_Policemen']+df['Police_Killed_Total_Policemen']+df['Cases_Registered_under_Human_Rights_Violations']
df['TotalCrime']

0         8308.0
1         8250.0
2        11636.0
3         6280.0
4        13014.0
          ...   
69658        0.0
69659        0.0
69660        0.0
69661        0.0
69662        0.0
Name: TotalCrime, Length: 69663, dtype: float64

In [68]:
l_vs_tc=df.groupby(['Literacy','State'])['TotalCrime'].sum().sort_values(ascending=False)
l_vs_tc[:10]

Literacy  State         
69.32     MADHYA PRADESH    10239794.0
82.34     MAHARASHTRA        9506210.0
67.02     ANDHRA PRADESH     8656782.0
80.09     TAMIL NADU         8406144.0
67.68     UTTAR PRADESH      8052702.0
0.00      RAJASTHAN          7915508.0
75.36     KARNATAKA          6090248.0
94.00     KERALA             5957120.0
78.03     GUJARAT            5763554.0
0.00      BIHAR              5584290.0
Name: TotalCrime, dtype: float64

In [69]:
df['womenCrime']=df['Rape']+df['Kidnapping and Abduction']+df['Dowry Deaths']+df['Assault on women with intent to outrage her modesty']+df['Insult to modesty of Women']+df['Cruelty by Husband or his Relatives']+df['Importation of Girls']+df['OTHER IPC CRIMES']+df['TOTAL IPC CRIMES']+df['Other Crimes Against SCs']+df['Foeticide']+df['Exposure and abandonment']+df['Procuration of minor girls']+df['Buying of girls for prostitution']+df['Selling of girls for prostitution']
df['womenCrime']

0        6142.0
1        5258.0
2        7561.0
3        4604.0
4        9318.0
          ...  
69658       0.0
69659       0.0
69660       0.0
69661       0.0
69662       0.0
Name: womenCrime, Length: 69663, dtype: float64

In [70]:
l_vs_wtc=df.groupby(['Literacy','State'])['womenCrime'].sum().sort_values(ascending=False)
l_vs_wtc[:10]

Literacy  State         
69.32     MADHYA PRADESH    8071212.0
80.09     TAMIL NADU        6793806.0
82.34     MAHARASHTRA       6384614.0
0.00      RAJASTHAN         6102324.0
67.02     ANDHRA PRADESH    6043350.0
67.68     UTTAR PRADESH     6022232.0
94.00     KERALA            4912598.0
75.36     KARNATAKA         4627092.0
78.03     GUJARAT           4613710.0
0.00      BIHAR             4151538.0
Name: womenCrime, dtype: float64

In [71]:
#crime against women
df=df.groupby('State').sum()

wc=df.sort_values(by='womenCrime',ascending=False)['womenCrime'][:10]
wc

State
MADHYA PRADESH    8071212.0
TAMIL NADU        6793806.0
MAHARASHTRA       6384614.0
RAJASTHAN         6102324.0
ANDHRA PRADESH    6043350.0
UTTAR PRADESH     6022232.0
KERALA            4912598.0
KARNATAKA         4627092.0
GUJARAT           4613710.0
BIHAR             4151538.0
Name: womenCrime, dtype: float64

In [72]:
df=df.groupby('State').sum()

tc=df.sort_values(by='TotalCrime',ascending=False)['TotalCrime'][:10]
tc

State
MADHYA PRADESH    10239794.0
MAHARASHTRA        9506210.0
ANDHRA PRADESH     8656782.0
TAMIL NADU         8406144.0
UTTAR PRADESH      8052702.0
RAJASTHAN          7915508.0
KARNATAKA          6090248.0
KERALA             5957120.0
GUJARAT            5763554.0
BIHAR              5584290.0
Name: TotalCrime, dtype: float64

In [73]:
tt_crime=df.groupby(['State'])['TotalCrime'].sum().sort_values(ascending=False)
tt_crime

State
MADHYA PRADESH          10239794.0
MAHARASHTRA              9506210.0
ANDHRA PRADESH           8656782.0
TAMIL NADU               8406144.0
UTTAR PRADESH            8052702.0
                           ...    
Dadra & Nagar Haveli           0.0
Daman & Diu                    0.0
Delhi UT                       0.0
JAMMU AND KASHMIR              0.0
 WEST BENGAL                   0.0
Name: TotalCrime, Length: 88, dtype: float64

2.2	 Analysis of the type of crime vs each state vs Literacy rate.

In [74]:
t_murder=df.groupby(['State','Literacy'])['Murder'].sum().sort_values(ascending=False)
t_murder

State                   Literacy 
UTTAR PRADESH           297927.36    148050.0
BIHAR                   0.00          84798.0
MAHARASHTRA             228246.48     71140.0
ANDHRA PRADESH          124791.24     66594.0
MADHYA PRADESH          218496.64     63232.0
                                       ...   
DAMAN AND DIU           87.10             0.0
Nagaland                0.00              0.0
DADRA AND NAGAR HAVELI  76.24             0.0
Odisha                  0.00              0.0
 WEST BENGAL            76.26             0.0
Name: Murder, Length: 88, dtype: float64

In [75]:
ta_murder=df.groupby(['State','Literacy'])['Attempt to murder'].sum().sort_values(ascending=False)
ta_murder

State                   Literacy 
UTTAR PRADESH           297927.36    121040.0
BIHAR                   0.00          81838.0
MADHYA PRADESH          218496.64     58916.0
TAMIL NADU              188772.13     53194.0
ANDHRA PRADESH          124791.24     44840.0
                                       ...   
DAMAN AND DIU           87.10             0.0
Nagaland                0.00              0.0
DADRA AND NAGAR HAVELI  76.24             0.0
Odisha                  0.00              0.0
 WEST BENGAL            76.26             0.0
Name: Attempt to murder, Length: 88, dtype: float64

In [76]:
ch_murder=df.groupby(['State','Literacy'])['Culpable homicide not amounting to muder'].sum().sort_values(ascending=False)
ch_murder

State           Literacy 
UTTAR PRADESH   297927.36    34532.0
WEST BENGAL     0.00         12666.0
BIHAR           0.00          7344.0
KERALA          110638.00     3794.0
MADHYA PRADESH  218496.64     3668.0
                              ...   
A&N Islands     0.00             0.0
Lakshadweep     0.00             0.0
Madhya Pradesh  0.00             0.0
Maharashtra     0.00             0.0
 WEST BENGAL    76.26            0.0
Name: Culpable homicide not amounting to muder, Length: 88, dtype: float64

In [77]:
kidnap=df.groupby(['State','Literacy'])['Kidnapping and Abduction'].sum().sort_values(ascending=False)
kidnap

State                   Literacy 
UTTAR PRADESH           297927.36    255176.0
BIHAR                   0.00         128632.0
RAJASTHAN               0.00         121676.0
ASSAM                   131457.99    102491.0
WEST BENGAL             0.00         101190.0
                                       ...   
DAMAN AND DIU           87.10             0.0
Nagaland                0.00              0.0
DADRA AND NAGAR HAVELI  76.24             0.0
Odisha                  0.00              0.0
 WEST BENGAL            76.26             0.0
Name: Kidnapping and Abduction, Length: 88, dtype: float64

In [78]:
dacoity=df.groupby(['State','Literacy'])['Dacoity'].sum().sort_values(ascending=False)
dacoity

State                   Literacy 
BIHAR                   0.00         22256.0
MAHARASHTRA             228246.48    16628.0
JHARKHAND               0.00         11868.0
UTTAR PRADESH           297927.36     9728.0
ASSAM                   131457.99     8402.0
                                      ...   
DAMAN AND DIU           87.10            0.0
Nagaland                0.00             0.0
DADRA AND NAGAR HAVELI  76.24            0.0
Odisha                  0.00             0.0
 WEST BENGAL            76.26            0.0
Name: Dacoity, Length: 88, dtype: float64

In [79]:
Riots=df.groupby(['State','Literacy'])['Riots'].sum().sort_values(ascending=False)
Riots

State          Literacy 
BIHAR          0.00         210192.0
KERALA         110638.00    192548.0
MAHARASHTRA    228246.48    180488.0
KARNATAKA      151247.52    156842.0
UTTAR PRADESH  297927.36    108220.0
                              ...   
Meghalaya      0.00              0.0
Mizoram        0.00              0.0
Nagaland       0.00              0.0
D&N Haveli     0.00              0.0
 WEST BENGAL   76.26             0.0
Name: Riots, Length: 88, dtype: float64

In [80]:
p_dacoity=df.groupby(['State','Literacy'])['Preparation and assembly for dacoity'].sum().sort_values(ascending=False)
p_dacoity

State         Literacy 
WEST BENGAL   0.00         21614.0
MAHARASHTRA   228246.48     7314.0
KARNATAKA     151247.52     5426.0
HARYANA       0.00          4840.0
KERALA        110638.00     3558.0
                            ...   
Kerala        0.00             0.0
A&N Islands   0.00             0.0
Lakshadweep   0.00             0.0
MIZORAM       50414.16         0.0
 WEST BENGAL  76.26            0.0
Name: Preparation and assembly for dacoity, Length: 88, dtype: float64

In [81]:
Robbery=df.groupby(['State','Literacy'])['Robbery'].sum().sort_values(ascending=False)
Robbery

State           Literacy 
MAHARASHTRA     228246.48    75660.0
UTTAR PRADESH   297927.36    61962.0
BIHAR           0.00         47494.0
MADHYA PRADESH  218496.64    44866.0
KARNATAKA       151247.52    34620.0
                              ...   
A&N Islands     0.00             0.0
Lakshadweep     0.00             0.0
Madhya Pradesh  0.00             0.0
Maharashtra     0.00             0.0
 WEST BENGAL    76.26            0.0
Name: Robbery, Length: 88, dtype: float64

In [82]:
Burglary=df.groupby(['State','Literacy'])['Burglary'].sum().sort_values(ascending=False)
Burglary

State                   Literacy 
MAHARASHTRA             228246.48    371234.0
MADHYA PRADESH          218496.64    274692.0
ANDHRA PRADESH          124791.24    194672.0
KARNATAKA               151247.52    146596.0
UTTAR PRADESH           297927.36    131174.0
                                       ...   
DAMAN AND DIU           87.10             0.0
Nagaland                0.00              0.0
DADRA AND NAGAR HAVELI  76.24             0.0
Odisha                  0.00              0.0
 WEST BENGAL            76.26             0.0
Name: Burglary, Length: 88, dtype: float64

In [83]:
Theft=df.groupby(['State','Literacy'])['Theft'].sum().sort_values(ascending=False)
Theft

State                   Literacy 
MAHARASHTRA             228246.48    1113614.0
UTTAR PRADESH           297927.36     624094.0
ANDHRA PRADESH          124791.24     574380.0
MADHYA PRADESH          218496.64     527720.0
RAJASTHAN               0.00          465948.0
                                       ...    
DAMAN AND DIU           87.10              0.0
Nagaland                0.00               0.0
DADRA AND NAGAR HAVELI  76.24              0.0
Odisha                  0.00               0.0
 WEST BENGAL            76.26              0.0
Name: Theft, Length: 88, dtype: float64

In [84]:
tTheft=df.groupby(['State','Literacy'])['TOTAL - Theft'].sum().sort_values(ascending=False)
tTheft

State                 Literacy 
TOTAL (STATES)        0.00         3240300.0
TOTAL (ALL-INDIA)     0.00         3205333.0
MAHARASHTRA           228246.48     556807.0
UTTAR PRADESH         297927.36     312047.0
ANDHRA PRADESH        124791.24     287190.0
                                     ...    
Nagaland              0.00               0.0
Dadra & Nagar Haveli  0.00               0.0
Odisha                0.00               0.0
DELHI UT              0.00               0.0
 WEST BENGAL          76.26              0.0
Name: TOTAL - Theft, Length: 88, dtype: float64

In [85]:
hurt=df.groupby(['State','Literacy'])['Hurt'].sum().sort_values(ascending=False)
hurt

State                   Literacy 
ANDHRA PRADESH          124791.24    1110192.0
MADHYA PRADESH          218496.64     850696.0
MAHARASHTRA             228246.48     709380.0
TAMIL NADU              188772.13     566046.0
RAJASTHAN               0.00          549456.0
                                       ...    
DAMAN AND DIU           87.10              0.0
Nagaland                0.00               0.0
DADRA AND NAGAR HAVELI  76.24              0.0
Odisha                  0.00               0.0
 WEST BENGAL            76.26              0.0
Name: Hurt, Length: 88, dtype: float64

In [86]:
poa=df.groupby(['State','Literacy'])['Prevention of atrocities (POA) Act'].sum().sort_values(ascending=False)
poa

State             Literacy 
UTTAR PRADESH     297927.36    53052.0
BIHAR             0.00         47832.0
ANDHRA PRADESH    124791.24    35372.0
KARNATAKA         151247.52    30924.0
ODISHA            0.00         24836.0
                                ...   
Himachal Pradesh  0.00             0.0
Haryana           0.00             0.0
Gujarat           0.00             0.0
Goa               0.00             0.0
 WEST BENGAL      76.26            0.0
Name: Prevention of atrocities (POA) Act, Length: 88, dtype: float64

In [87]:
pcr=df.groupby(['State','Literacy'])['Protection of Civil Rights (PCR) Act'].sum().sort_values(ascending=False)
pcr

State           Literacy 
ANDHRA PRADESH  124791.24    3260.0
KARNATAKA       151247.52    1014.0
TAMIL NADU      188772.13    1010.0
UTTAR PRADESH   297927.36    1002.0
BIHAR           0.00          978.0
                              ...  
Haryana         0.00            0.0
Gujarat         0.00            0.0
Goa             0.00            0.0
Delhi UT        0.00            0.0
 WEST BENGAL    76.26           0.0
Name: Protection of Civil Rights (PCR) Act, Length: 88, dtype: float64

In [88]:
st=df.groupby(['State','Literacy'])['Other Crimes Against STs'].sum().sort_values(ascending=False)
st

State           Literacy 
MADHYA PRADESH  218496.64    18830.0
RAJASTHAN       0.00         17480.0
ANDHRA PRADESH  124791.24     7088.0
CHHATTISGARH    94104.92      5912.0
ODISHA          0.00          3908.0
                              ...   
A&N Islands     0.00             0.0
Lakshadweep     0.00             0.0
MEGHALAYA       36619.56         0.0
MIZORAM         50414.16         0.0
 WEST BENGAL    76.26            0.0
Name: Other Crimes Against STs, Length: 88, dtype: float64

In [89]:
sc=df.groupby(['State','Literacy'])['Other Crimes Against SCs'].sum().sort_values(ascending=False)
sc

State           Literacy 
RAJASTHAN       0.00         75306.0
UTTAR PRADESH   297927.36    68588.0
MADHYA PRADESH  218496.64    61442.0
ANDHRA PRADESH  124791.24    34824.0
KARNATAKA       151247.52    14910.0
                              ...   
Lakshadweep     0.00             0.0
MANIPUR         49010.78         0.0
MEGHALAYA       36619.56         0.0
MIZORAM         50414.16         0.0
 WEST BENGAL    76.26            0.0
Name: Other Crimes Against SCs, Length: 88, dtype: float64

In [90]:
ipc=df.groupby(['State','Literacy'])['TOTAL IPC CRIMES'].sum().sort_values(ascending=False)
ipc

State                   Literacy 
MADHYA PRADESH          218496.64    4827540.0
MAHARASHTRA             228246.48    4546872.0
TAMIL NADU              188772.13    4120352.0
ANDHRA PRADESH          124791.24    4037962.0
UTTAR PRADESH           297927.36    3716148.0
                                       ...    
DAMAN AND DIU           87.10              0.0
Nagaland                0.00               0.0
DADRA AND NAGAR HAVELI  76.24              0.0
Odisha                  0.00               0.0
 WEST BENGAL            76.26              0.0
Name: TOTAL IPC CRIMES, Length: 88, dtype: float64

2.3	Analysis of year-on-year total crime rate.

1.Uttar Pradesh has the highest number of murder cases,Attempt to murder cases,Culpable homicide not amounting to muder cases,Kidnapping and Abduction cases,Prevention of atrocities (POA) Act 2.Bihar has the highest number of Dacoity, Riots cases 3.WEST BENGAL has 21614.0 cases of Preparation and assembly for dacoity 4.MAHARASHTRA 75660.0 has highest number of robbery cases,Burglary cases,Theft cases 5.ANDHRA PRADESH has most no of Hurt cases ,Protection of Civil Rights (PCR) Act cases 6.Madhya Pradesh has most no of cases against Other Crimes Against STs and rajasthan agaisnt Sc 7.The Top 3 states having most no of IPC crimes is Madhya Pradesh,Maharashtra and TamilNadu 8.The top 3 states having most no of crime against Women is Madhya Pradesh,TamilNadu and Maharashtra 9.Most no of crimes are found in MADHYA PRADESH,MAHARASHTRA ,ANDHRA PRADESH 10.We can also see the literacy rates are 69 for MP, 82 for MH and 67 for AP and 67.68 for UP where crimes are also very much
11.We can see that literacy,area,population does affect the Crime rates.


Phase 3
SQL Operations

In [91]:
import csv
import sqlite3
import pyodbc

In [92]:
conn = sqlite3.connect( database='women.db')

In [94]:
cursor = conn.cursor()

In [95]:
pyodbc.drivers()

['SQL Server']

In [96]:
df=pd.read_csv(r"E:\India_Crime - Copy\42_District_wise_crimes_committed_against_women_2001_2012.csv")

In [ ]:
import pandas as pd
import sqlite3  # For PostgreSQL, you might need to install this package

# Step 1: Connect to your database
conn = sqlite3.connect(database='women.db')

# Step 2: Create a table (Assuming PostgreSQL for this example)
create_table_query = """
CREATE TABLE crimes_against_women (
    district_code INT,
    district_name VARCHAR(255),
    year INT,
    rape_cases INT,
    kidnapping_abduction_cases INT,
    dowry_deaths INT,
    assault_on_women_with_intent_to_outrage_her_modesty INT,
    insult_to_modesty_of_women INT,
    cruelty_by_husband_or_his_relatives INT,
    importation_of_girls INT,
    abetment_of_suicide_of_women INT,
    dowry_prohibition_act INT,
    indecent_representation_of_women INT,
    sati_prevention_act INT,
    immoral_traffic_prevention_act INT,
    total_crimes INT
);
"""
cur = conn.cursor()
cur.execute(create_table_query)
conn.commit()

# Step 3: Read the CSV file and insert records into the table
df = pd.read_csv('42_District_wise_crimes_committed_against_women_2001_2012.csv')

# Iterate through the rows and insert them into the table
for index, row in df.iterrows():
    insert_query = """
    INSERT INTO crimes_against_women (
        district_code, district_name, year, rape_cases, kidnapping_abduction_cases,
        dowry_deaths, assault_on_women_with_intent_to_outrage_her_modesty,
        insult_to_modesty_of_women, cruelty_by_husband_or_his_relatives,
        importation_of_girls, abetment_of_suicide_of_women, dowry_prohibition_act,
        indecent_representation_of_women, sati_prevention_act,
        immoral_traffic_prevention_act, total_crimes
    )
    VALUES (
        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
    )
    """
    data = (
        row['District_code'], row['District_Name'], row['Year'], row['Rape_Cases'],
        row['Kidnapping_Abduction_Cases'], row['Dowry_Deaths'],
        row['Assault_on_women_with_intent_to_outrage_her_modesty'],
        row['Insult_to_modesty_of_Women'], row['Cruelty_by_Husband_or_his_relatives'],
        row['Importation_of_Girls'], row['Abetment_of_Suicide_of_Women'],
        row['Dowry_Prohibition_Act'], row['Indecent_Representation_of_Women'],
        row['Sati_Prevention_Act'], row['Immoral_Traffic_Prevention_Act'],
        row['Total_Crimes']
    )
    cur.execute(insert_query, data)

conn.commit()
conn.close()
